import Head from 'next/head';
import react, { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';

import { useUser } from '../lib/hooks';
import Layout from '../components/Layout';

import Table from '../components/Table';

const columns = [
  {
    name: 'First name',
    key: 'first_name',
  },
  {
    name: 'Last name',
    key: 'last_name',
  },
  {
    name: 'Email',
    key: 'email',
  },
];

export default function Home() {
  const user = useUser();

  const [data, setData] = useState([]);
  const [cursor, setCursor] = useState(1);
  const [total, setTotal] = useState(0);
  const [hasMore, setHasMore] = useState(true);

  useEffect(() => {
    fetch(`https://reqres.in/api/users?page=${cursor}`)
      .then((e) => e.json())
      .then((v) => {
        setTotal(v.total);
        setData((e) => [...e, ...v.data]);
        setHasMore(v.page < v.total_pages);
      });
  }, [cursor]);

  const loadMore = () => setCursor((p) => p + 1);

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {user && (
          <>
            <p>Currently logged in as:</p>
            <pre>{JSON.stringify(user, null, 2)}</pre>
          </>
        )}

        {user && <Table
          columns={columns}
          tableData={data}
          currPage={1}
          perPage={5}
          total={total}
          loadMore={loadMore}
          hasMore={hasMore}
        />}
      </main>

      <footer className={styles.footer}>footer</footer>
    </Layout>
  );
}
