import Head from 'next/head';
import react, { useState } from 'react';
import styles from '../styles/Home.module.css';

import Table from '../components/table';
import { useEffect } from 'react';

const columns = [
  {
    name: 'First name',
    key: 'first_name',
  },
  {
    name: 'Last name',
    key: 'last_name',
  },
  {
    name: 'Email',
    key: 'email',
  },
];

const data = [];

export default function Home() {
  const [users, setUsers] = useState([]);
  const [cursor, setCursor] = useState(1);
  const [total, setTotal] = useState(0);

  useEffect(() => {
    fetch(`https://reqres.in/api/users?page=${cursor}`)
      .then((e) => e.json())
      .then((v) => {
        setTotal(v.total)
        setUsers((e) => [...e, ...v.data])
      });
  }, [cursor]);

  const loadMore = () => setCursor((p) => p + 1);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {(
          <Table columns={columns} tableData={users} currPage={1} perPage={5} total={total} loadMore={loadMore}/>
        )}
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
}
